# Generated by Django 5.0.7 on 2025-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.TextField()),
                ('cipher_text', models.TextField()),
                ('encryption_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SecretDocument',
        ),
    ]
